### ISSUE TITLE
ingest trait table data from

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#2]
From this resource and paper:
https://github.com/bacteria-archaea-traits/bacteria-archaea-traits
https://www.nature.com/articles/s41597-020-0497-4

Specifically the output file with NCBI taxon ids:
https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/blob/master/output/condensed_traits_NCBI.csv

**Comment by cmungall** [comment]
@realmarcin is this done? also remember to assign tickets!

**Comment by cmungall** [comment]
One of the tasks here is to provide a brief description of how each column is mapped

**Comment by realmarcin** [comment]
This is done for now, but future iterations will involve further concept and relationship modeling.
