### ISSUE TITLE
strain:of_NO_NCBITaxon_ID from bacdive lead to clashes

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#211]
strain:of_NO_NCBITaxon_ID       biolink:capable_of      EC:1.11.1.6     RO:0002200      bacdive:166308
strain:of_NO_NCBITaxon_ID       biolink:capable_of      EC:3.1.3.1      RO:0002200      bacdive:166308
strain:of_NO_NCBITaxon_ID       biolink:consumes        CHEBI:17295     RO:0000057      bacdive:159791
strain:of_NO_NCBITaxon_ID       biolink:capable_of      EC:3.4.11.1     RO:0002200      bacdive:166308

**Comment by bsantan** [comment]
This is due to special characters in the taxonomy strings, should deal with that in the future.

**Comment by realmarcin** [comment]
fixed
