### ISSUE TITLE
bacdive strain ids with single chars eg strain:1 are leading to clashes

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#213]

**Comment by realmarcin** [comment]
@hrshdhgd still a new nodes with single char names in latest merge from your NERSC dir:

strain:2        biolink:OrganismTaxon   2
strain:4        biolink:OrganismTaxon   4
strain:7        biolink:OrganismTaxon   7
strain:A        biolink:OrganismTaxon   Providencia sneebia Juneja and Lazzaro 2009
strain:B        biolink:OrganismTaxon   Salinivibrio sharmensis Romano et al. 2011
strain:C        biolink:OrganismTaxon   Methylovorus mays Doronina et al. 2001 emend. Doronina et al. 2005
strain:D        biolink:OrganismTaxon   Allochromatium vinosum (Ehrenberg 1838) Imhoff et al. 1998
strain:E        biolink:OrganismTaxon   Sporomusa sphaeroides MÃ¶ller et al. 1985
strain:F        biolink:OrganismTaxon   Methanobacterium palustre Zellner et al. 1990
strain:G        biolink:OrganismTaxon   Leuconostoc fallax Martinez-Murcia and Collins 1992
strain:H        biolink:OrganismTaxon   Turneriella parva (Hovind-Hougen et al. 1982) Levett et al. 2005
strain:I        biolink:OrganismTaxon   Paucilactobacillus suebicus (Kleynmans et al. 1989) Zheng et al. 2020
strain:J        biolink:OrganismTaxon   Alcaligenes faecalis subsp. phenolicus Rehfuss and Urban 2006
strain:K        biolink:OrganismTaxon   Marinospirillum insulare Satomi et al. 2004
strain:M        biolink:OrganismTaxon   Methanothermobacter thermophilus (Laurinavichus et al. 1990) Boone 2002
strain:N        biolink:OrganismTaxon   Flavobacterium hydatis Bernardet et al. 1996 emend. Hahnke et al. 2016
strain:O        biolink:OrganismTaxon   Haliscomenobacter hydrossis van Veen et al. 1973 emend. Hahnke et al. 2016
strain:P        biolink:OrganismTaxon   Thiospirochaeta perfilievii (Dubinina et al. 2011) Dubinina et al. 2020
strain:Q        biolink:OrganismTaxon   Thiothrix fructosivorans Howarth et al. 1999
strain:S        biolink:OrganismTaxon   Magnetospirillum molischianum (Giesberger 1947) HÃ¶rdt et al. 2020
strain:T        biolink:OrganismTaxon   Symbiobacterium thermophilum Ohno et al. 2000
strain:U        biolink:OrganismTaxon   Geobacillus uzenensis Nazina et al. 2001
strain:V        biolink:OrganismTaxon   Acidiplasma aeolicum Golyshina et al. 2009
strain:W        biolink:OrganismTaxon   Clostridium acetobutylicum McCoy et al. 1926 emend. Keis et al. 2001
strain:X        biolink:OrganismTaxon   Sporomusa paucivorans Hermann et al. 1987
strain:Y        biolink:OrganismTaxon   Ferroplasma acidiphilum Golyshina et al. 2000
strain:Z        biolink:OrganismTaxon   strain_of Methylobacillus methanolivorans

**Comment by realmarcin** [comment]
There are more clashes with strain ids. The suggested solution is to use the strain:bacdive_XXXX id for bacdive strains. The only exception if if we can use the NCBITaxon id.

The rule for the label is:

<strain designation> of <NCBITaxon id>

This should be done for all bacdive strains which don't have a NCBITaxon according to our rules.


Some more example of dual strain ids:

strain:c1       biolink:OrganismTaxon   Chitinilyticum litopenaei Chang et al. 2009
strain:c2       biolink:OrganismTaxon   Halothiobacillus neapolitanus (Parker 1957) Kelly and Wood 2000 emend. Boden 2017
strain:hg       biolink:OrganismTaxon   strain_of Flavobacterium yanchengense
strain:ps       biolink:OrganismTaxon   Methanospirillum stamsii Parshina et al. 2014
strain:t2       biolink:OrganismTaxon   Brevundimonas vesicularis (BÃ¼sing et al. 1953) Segers et al. 1994
(nersc-python) (venv) marcinj@perlmutter:login28:/global/cfs/cdirs/m4689/current>

**Comment by realmarcin** [comment]
Old id -> new id

Old:
NCBITaxon:296   biolink:OrganismTaxon   Pseudomonas fragi

New:
id: bacdive_165157
label: bacdive_165157 of NCBITaxon:296

Another case of NCBITaxon:296:
id: bacdive_100179
label: bacdive_100179 as STI09555(IMET), T-V of NCBITaxon:296

**Comment by realmarcin** [comment]
Missing bacdive ids in nodes files:
bacdive:165157
bacdive:165236
bacdive:165224
bacdive:165230
bacdive:165223

**Comment by hrshdhgd** [comment]
> Missing bacdive ids in nodes files: bacdive:165157 bacdive:165236 bacdive:165224 bacdive:165230 bacdive:165223

These are coming from mediadive

**Comment by hrshdhgd** [comment]
As per discussion: 

 - Comment out `bacdive:XXX`
 - Make sure the bacdive IDs eliminated from above are included in the `BacDive Transform`
