### ISSUE TITLE
example of media missing ingredients in merge

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#215]
it looks like one of the popular media is missing of edges for different ingredients:
urn:uuid:4c45f312-4316-4bf6-b8bb-ea5d155ccbfc	medium:514	biolink:has_part	solution:1134	BFO:0000051	Graph		https://mediadive.dsmz.de/rest/solution/1134

There are 93 has_part edges in the mediadive transform file:
grep medium:514 edges.tsv | grep has_part | wc
      93     465    9198
      
Source reference here (but really our download):
https://mediadive.dsmz.de/medium/514

@hrshdhgd

**Comment by hrshdhgd** [comment]
Seems like a KGX merge issue. When our final merge is ready we can look for this.

**Comment by realmarcin** [comment]
just noting here that the example @hrshdhgd posted was for dropping nodes whereas this ticket is for dropping edges. Not sure yet if those are related ...

**Comment by hrshdhgd** [comment]
Both nodes and edges were being dropped.

**Comment by realmarcin** [comment]
Closing this issue because it is due to data modeling - in this case the solution is the same as the medium, and all of the ingredients are edges to solution.
