### ISSUE TITLE
empty object for strain: subclass_of

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#216]
empty object for strain: subclass_of, e.g. in bacdive transform:

strain:108^Ibiolink:subclass_of^I^Irdfs:subClassOf^Ibacdive:140012$

Looks like 96 of these in the latest bacdive transform:

grep -E ‘of            ’ ../../kg-microbe/data/merged/20240702/bacdive_edges.tsv  |wc
96

A mix of cases:
strain:ZE-1     biolink:subclass_of             rdfs:subClassOf bacdive:16803
strain:of_NO_NCBITaxon_ID       biolink:subclass_of             rdfs:subClassOf bacdive:16401 

@hrshdhgd

**Comment by hrshdhgd** [comment]
> grep -E ‘of ’ ../../kg-microbe/data/merged/20240702/bacdive_edges.tsv |wc
> 96

It's 0 for me. Your version may be old.

**Comment by hrshdhgd** [comment]
> A mix of cases:
> strain:ZE-1 biolink:subclass_of rdfs:subClassOf bacdive:16803
> strain:of_NO_NCBITaxon_ID biolink:subclass_of rdfs:subClassOf bacdive:16401

Does not exist in the latest versions

**Comment by hrshdhgd** [comment]
> strain:108^Ibiolink:subclass_of^I^Irdfs:subClassOf^Ibacdive:140012$

This is the only one I found in the latest version ...fixing.
