### ISSUE TITLE
bacdive nodes from mediadive are redundant and not normalized against bacdive ingest

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#221]
This is a mediadive record:
- bacdive_id: 133349
  ccno: JCM 31401
  domain: B
  growth: 1
  id: 40227
  species: Methylobacillus methanolivorans

so these are already strain or NCBITaxon from BacDive … so easy normalization we are not doing

Ah ok, but Harshad is saying that these ids are not found in the BacDive json …

However, I can find this one  in bacdive.json:
 “133349”: {
        “General”: {
            “@ref”: 25194,
            “BacDive-ID”: 133349,
            “keywords”: [
                “colony-forming”,
                “rod-shaped”,
                “motile”,
                “Gram-negative”,
                “methylotroph”,
                “obligate aerobe”,
                “Bacteria”,
                “16S sequence”
            ],
            “description”: “Methylobacillus methanolivorans Z is an obligate aerobe, methylotroph, Gram-negative bacterium that forms circular colonies and was isolated from activated sludge of the drainage system.“,
            “NCBI tax id”: {
                “NCBI tax id”: 1848927,
                “Matching level”: “species”
            },
            “strain history”: “N. V. Doronina; G. K. Skryabin Inst. of Biochem. & Physiol. of Microorg., RAS, Russia; Z.“,
            “doi”: “10.13145/bacdive133349.20220920.7"
        },
(https://monarchinitiative.slack.com/archives/C06JDL03NM9/p1724355543485049)
So I think we need to link these two ingests a little more and use the same strain: or NCBITaxon: we used in the bacdive ingest so they link up.

I checked a few more of the mediadive bacdive ids and all are found in the bacdive.json 

The big issues with the current bacdive: nodes from mediadive are:
they are redundant with taxon nodes from bacdive (but different id)
they have no subclass edges to taxonomy
they have medium edges but no traits (because traits are assigned to the taxon node from bacdive ingest)

 I do see them in the taxonomy and phyiosology tsv:
bacdive_name_tax_classification.tsv:bacdive:133349
bacdive_physiology_metabolism.tsv:bacdive:133349

@hrshdhgd

**Comment by hrshdhgd** [comment]
Fixed by https://github.com/Knowledge-Graph-Hub/kg-microbe/pull/222
