### ISSUE TITLE
new strain:bacdive_ nodes are missing edges to medium: nodes

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#223]
Turns out that in the latest merge the new strain:bacdive_ nodes do not have any medium: edges:

grep strain:bacdive_ merged-kg_nodes.tsv   | wc
  18537  139009 1890855

We do have a number of edges for these nodes but they are all subclassof:

grep strain:bacdive_ merged-kg_edges.tsv | wc
  18443  129101 2634734

@hrshdhgd

**Comment by hrshdhgd** [comment]
Fixed by https://github.com/Knowledge-Graph-Hub/kg-microbe/pull/224
