### ISSUE TITLE
ingest biosafety data from BacDive

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#243]
The section for each taxon in the bacdive json look like this:

"Safety information": {
            "risk assessment": {
                "@ref": 20215,
                "biosafety level": "1",
                "biosafety level comment": "Risk group"
            }
        },

This would correspond to the edge:

Taxon ->  biolink:associated_with -> BSL:1

so its just a matter of getting the integer from  "biosafety level": "1" and turning into a CURIE with the BSL: prefix.

Overall there are four permissible values here 1,2,3,4 and I think bacdive has no cases of 4.

@hrshdhgd

**Comment by hrshdhgd** [comment]
What would be the category for biosafety? For now I'm using `"biolink:Attribute"`

**Comment by hrshdhgd** [comment]
Also there's levels => `L1`, `1+` in addition to 1, 2 and 3. There was `3**` which I stripped to 3.
