### ISSUE TITLE
review Madin et al. trait data -- can have multiple rows for taxonid

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#245]
Here is one example 908615 -- what happens in this case? Do we aggregate edges from the three rows to one taxon node?

908615,908615,"engqvist"	"psychroflexus_halocasei"	"Psychroflexus halocasei"	"Psychroflexus"	"Flavobacteriaceae"	"Flavobacteriales"	"Flavobacteriia"	"Bacteroidetes"	"Bacteria",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"28",NA,NA,705
908615,908615,"fierer"	"Psychroflexus halocasei"	"Psychroflexus halocasei"	"Psychroflexus"	"Flavobacteriaceae"	"Flavobacteriales"	"Flavobacteriia"	"Bacteroidetes"	"Bacteria",NA,"obligate aerobic",NA,"alanine, asparagine, dextrin, lactate, maltose, ornithine, propionate, Tween 80",NA,"no",NA,NA,"bacillus"	"food"	"0.55",NA,"3",NA,NA,NA,NA,NA,"28.5"	"7.5",NA,NA,NA,4679
908615,908615,"gold"	"Psychroflexus halocasei DSM 23581"	"Psychroflexus halocasei"	"Psychroflexus"	"Flavobacteriaceae"	"Flavobacteriales"	"Flavobacteriia"	"Bacteroidetes"	"Bacteria",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2671918",NA,NA,NA,NA,NA,NA,NA,13521

@hrshdhgd

**Comment by hrshdhgd** [comment]
As of now for Madin et. al. transform. They are 3 separate nodes since the labels are different (needs to be normalized) but they all map to  a single ID => `NCBITaxon:908615`.

In terms of edges, it should not matter sine the ID is the same
