### ISSUE TITLE
double check cell length and width values

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-microbe#247]
just a note that I'm only seeing these four dimension related terms in our current merge. This is from BactoTraits and the raw data table has 4 values for each of width and length:

W_<=0.5 W_0.5_0.65 W_0.65_0.9 W_>0.9 L_<=1.3 L_1.3_2 L_2_3 L_>3

@hrshdhgd

**Comment by hrshdhgd** [comment]
I do not follow:

![Screenshot 2024-09-17 at 11 04 04 AM](https://github.com/user-attachments/assets/0d6c7539-4e56-4597-a406-3d91fffdbbd1)

![Screenshot 2024-09-17 at 11 03 44 AM](https://github.com/user-attachments/assets/2a9732d3-d647-4a9b-a4a9-7ba61614180e)

**Comment by hrshdhgd** [comment]
You mean just `very_low` and `high` ?

**Comment by hrshdhgd** [comment]
Found the bug ...fixing
