### ISSUE TITLE
add support for Jenkins builds/pushing to S3

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-microbe#8]
Similar to KG-COVID-19, set up Jenkins to run build on build.berkeleybop.io, and push to S3, probably http://kg-hub.berkeleybop.io/kg-microbe, per convo with @cmungall. 

[kg-covid-19 Jenkinsfile](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/Jenkinsfile) for reference

**Comment by hrshdhgd** [comment]
This is complete: PRs #22 , #23 and  #25
